<?php

namespace Tests\Todo\Feature\Http\Controllers;

use App\Models\User;
use App\Models\Warning;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\WarningController
 */
class WarningControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function delete_all_warnings_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();
        Warning::factory()->create(['user_id' => $user->id]);

        $response = $this->actingAs($user)->delete(route('users.warnings.massDestroy', ['user' => $user]));

        $response->assertRedirect(withSuccess('All Warnings Were Successfully Deleted'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_warning_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();
        $warning = Warning::factory()->create(['user_id' => $user]);

        $response = $this->actingAs($user)->delete(route('users.warnings.destroy', ['user' => $user, 'warning' => $warning]));

        $response->assertRedirect(withSuccess('Warning Was Successfully Deleted'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_warning_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();
        $warning = Warning::factory()->create(['user_id' => $user]);

        $response = $this->actingAs($user)->get(route('users.warnings.update', ['user' => $user, 'warning' => $warning]));

        $response->assertRedirect(withSuccess('Warning Was Successfully Restored'));

        // TODO: perform additional assertions
    }

    // test cases...
}
